---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://openedx.atlassian.net/wiki/display/OpenOPS
# code style: https://openedx.atlassian.net/wiki/display/OpenOPS/Ansible+Code+Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
# Defaults for role ecomworker.
#

ECOMMERCE_WORKER_GIT_IDENTITY: !!null
ECOMMERCE_WORKER_VERSION: 'master'

ECOMMERCE_WORKER_REPOS:
  - PROTOCOL: '{{ COMMON_GIT_PROTOCOL }}'
    DOMAIN: '{{ COMMON_GIT_MIRROR }}'
    PATH: '{{ COMMON_GIT_PATH }}'
    REPO: ecommerce-worker.git
    VERSION: '{{ ECOMMERCE_WORKER_VERSION }}'
    DESTINATION: '{{ ecommerce_worker_code_dir }}'
    SSH_KEY: '{{ ECOMMERCE_WORKER_GIT_IDENTITY }}'

# Requires that New Relic be enabled via COMMON_ENABLE_NEWRELIC, and that
# a key be provided via NEWRELIC_LICENSE_KEY.
ECOMMERCE_WORKER_NEWRELIC_APPNAME: '{{ COMMON_ENVIRONMENT }}-{{ COMMON_DEPLOYMENT }}-{{ ecommerce_worker_service_name }}'
ECOMMERCE_WORKER_ENABLE_NEWRELIC_DISTRIBUTED_TRACING: false

ECOMMERCE_WORKER_CONCURRENCY: 4
# END CELERY

# Long-lived access token used by Celery workers to authenticate against the ecommerce service.
ECOMMERCE_WORKER_WORKER_ACCESS_TOKEN: 'your-secret-here'

# Remote config
ECOMMERCE_WORKER_HERMES_ENABLED: "{{ COMMON_HERMES_ENABLED }}"

ecommerce_worker_environment:
  WORKER_CONFIGURATION_MODULE: 'ecommerce_worker.configuration.production'
  ECOMMERCE_WORKER_CFG: '{{ COMMON_CFG_DIR }}/{{ ecommerce_worker_service_name }}.yml'

ecommerce_worker_service_name: 'ecomworker'
ecommerce_worker_user: '{{ ecommerce_worker_service_name }}'
ecommerce_worker_home: '{{ COMMON_APP_DIR }}/{{ ecommerce_worker_service_name }}'
ecommerce_worker_code_dir: '{{ ecommerce_worker_home }}/{{ ecommerce_worker_service_name }}'

ecommerce_worker_log_dir: '{{ COMMON_LOG_DIR }}/{{ ecommerce_worker_service_name }}'

ecommerce_worker_requirements_base: '{{ ecommerce_worker_code_dir }}/requirements'
ecommerce_worker_requirements:
  - production.txt
  - optional.txt

# OS packages
ecommerce_worker_debian_pkgs: []
ecommerce_worker_redhat_pkgs: []
