---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://openedx.atlassian.net/wiki/display/OpenOPS
# code style: https://openedx.atlassian.net/wiki/display/OpenOPS/Ansible+Code+Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
##
# Defaults for role discovery
#

DISCOVERY_GIT_IDENTITY: !!null

#
# vars are namespace with the module name.
#
discovery_service_name: "discovery"
discovery_gunicorn_port: 8381

DISCOVERY_DEFAULT_DB_NAME: 'discovery'
DISCOVERY_MYSQL: 'localhost'
# MySQL usernames are limited to 16 characters
DISCOVERY_MYSQL_USER: 'discov001'
DISCOVERY_MYSQL_PASSWORD: 'password'
DISCOVERY_MYSQL_REPLICA_HOST: 'localhost'

discovery_environment:
  DISCOVERY_CFG: "{{ COMMON_CFG_DIR }}/{{ discovery_service_name }}.yml"
  DISCOVERY_MYSQL_REPLICA_HOST: '{{ DISCOVERY_MYSQL_REPLICA_HOST }}'
  DISCOVERY_MYSQL_REPLICA_USER: '{{ DISCOVERY_MYSQL_USER }}'
  DISCOVERY_MYSQL_REPLICA_PASSWORD: '{{ DISCOVERY_MYSQL_PASSWORD }}'
  DISCOVERY_MYSQL_REPLICA_NAME: '{{ DISCOVERY_DEFAULT_DB_NAME }}'

discovery_user: "{{ discovery_service_name }}"
discovery_home: "{{ COMMON_APP_DIR }}/{{ discovery_service_name }}"
discovery_code_dir: "{{ discovery_home }}/{{ discovery_service_name }}"

#
# OS packages
#

discovery_debian_pkgs:
  - libxml2-dev
  - libxslt-dev
  - libjpeg-dev


DISCOVERY_NGINX_PORT: "1{{ discovery_gunicorn_port }}"
DISCOVERY_SSL_NGINX_PORT: "4{{ discovery_gunicorn_port }}"

DISCOVERY_DEFAULT_DB_NAME: 'discovery'
DISCOVERY_MYSQL: 'localhost'
# MySQL usernames are limited to 16 characters
DISCOVERY_MYSQL_USER: 'discov001'
DISCOVERY_MYSQL_PASSWORD: 'password'

DISCOVERY_MEMCACHE: [ 'memcache' ]

DISCOVERY_VERSION: "master"
DISCOVERY_DJANGO_SETTINGS_MODULE: "course_discovery.settings.production"
DISCOVERY_URL_ROOT: 'http://discovery:{{ DISCOVERY_NGINX_PORT }}'
DISCOVERY_LOGOUT_URL: '{{ DISCOVERY_URL_ROOT }}/logout/'

DISCOVERY_SECRET_KEY: 'Your secret key here'

DISCOVERY_SESSION_EXPIRE_AT_BROWSER_CLOSE: false

# Used to automatically configure OAuth2 Client
DISCOVERY_SOCIAL_AUTH_EDX_OAUTH2_KEY: 'discovery-sso-key'
DISCOVERY_SOCIAL_AUTH_EDX_OAUTH2_SECRET: 'discovery-sso-secret'
DISCOVERY_BACKEND_SERVICE_EDX_OAUTH2_KEY: 'discovery-backend-service-key'
DISCOVERY_BACKEND_SERVICE_EDX_OAUTH2_SECRET: 'discovery-backend-service-secret'
# NOTE: Deprecate these OIDC settings post-DOP-removal for credentials.
DISCOVERY_SOCIAL_AUTH_EDX_OIDC_KEY : 'discovery-key'
DISCOVERY_SOCIAL_AUTH_EDX_OIDC_SECRET : 'discovery-secret'
DISCOVERY_SOCIAL_AUTH_REDIRECT_IS_HTTPS: false

DISCOVERY_DATA_DIR: '{{ COMMON_DATA_DIR }}/{{ discovery_service_name }}'
DISCOVERY_MEDIA_ROOT: '{{ DISCOVERY_DATA_DIR }}/media'
DISCOVERY_MEDIA_URL: '/media/'

DISCOVERY_MEDIA_STORAGE_BACKEND:
  DEFAULT_FILE_STORAGE: 'django.core.files.storage.FileSystemStorage'
  MEDIA_ROOT: '{{ DISCOVERY_MEDIA_ROOT }}'
  MEDIA_URL: '{{ DISCOVERY_MEDIA_URL }}'

DISCOVERY_STATICFILES_STORAGE: 'django.contrib.staticfiles.storage.StaticFilesStorage'

DISCOVERY_GUNICORN_EXTRA: ''

DISCOVERY_EXTRA_APPS: []

DISCOVERY_REPOS:
  - PROTOCOL: "{{ COMMON_GIT_PROTOCOL }}"
    DOMAIN: "{{ COMMON_GIT_MIRROR }}"
    PATH: "{{ COMMON_GIT_PATH }}"
    REPO: 'course-discovery.git'
    VERSION: "{{ DISCOVERY_VERSION }}"
    DESTINATION: "{{ discovery_code_dir }}"
    SSH_KEY: "{{ DISCOVERY_GIT_IDENTITY }}"

# See edx_django_service_automated_users for an example of what this should be
DISCOVERY_AUTOMATED_USERS: {}


DISCOVERY_ENABLE_NEWRELIC_DISTRIBUTED_TRACING: false

# Remote config
DISCOVERY_HERMES_ENABLED: "{{ COMMON_HERMES_ENABLED }}"
