---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://openedx.atlassian.net/wiki/display/OpenOPS
# code style: https://openedx.atlassian.net/wiki/display/OpenOPS/Ansible+Code+Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
##
# Role includes for role discovery
#
# Example:
#
# dependencies:
#   - {
#   role: my_role
#   my_role_var0: 'foo'
#   my_role_var1: 'bar'
# }
dependencies:
  - role: edx_django_service
    edx_django_service_repos: '{{ DISCOVERY_REPOS }}'
    edx_django_service_name: '{{ discovery_service_name }}'
    edx_django_service_user: '{{ discovery_user }}'
    edx_django_service_home: '{{ COMMON_APP_DIR }}/{{ discovery_service_name }}'
    edx_django_service_debian_pkgs_extra: '{{ discovery_debian_pkgs }}'
    edx_django_service_gunicorn_port: '{{ discovery_gunicorn_port }}'
    edx_django_service_django_settings_module: '{{ DISCOVERY_DJANGO_SETTINGS_MODULE }}'
    edx_django_service_environment_extra: '{{ discovery_environment }}'
    edx_django_service_gunicorn_extra: '{{ DISCOVERY_GUNICORN_EXTRA }}'
    edx_django_service_wsgi_name: 'course_discovery'
    edx_django_service_nginx_port: '{{ DISCOVERY_NGINX_PORT }}'
    edx_django_service_ssl_nginx_port: '{{ DISCOVERY_SSL_NGINX_PORT }}'
    edx_django_service_memcache: '{{ DISCOVERY_MEMCACHE }}'
    edx_django_service_automated_users: '{{ DISCOVERY_AUTOMATED_USERS }}'
    edx_django_service_enable_newrelic_distributed_tracing: '{{ DISCOVERY_ENABLE_NEWRELIC_DISTRIBUTED_TRACING }}'
