---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://openedx.atlassian.net/wiki/display/OpenOPS
# code style: https://openedx.atlassian.net/wiki/display/OpenOPS/Ansible+Code+Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
##
# Role includes for role ecommerce
#
dependencies:
  - role: edx_themes
    theme_users:
      - '{{ ecommerce_user }}'
    when: ECOMMERCE_ENABLE_COMPREHENSIVE_THEMING
  - role: edx_django_service
    edx_django_service_version: '{{ ECOMMERCE_VERSION }}'
    edx_django_service_name: '{{ ecommerce_service_name }}'
    edx_django_service_debian_pkgs_extra: '{{ ecommerce_debian_pkgs }}'
    edx_django_service_django_settings_module: '{{ ECOMMERCE_DJANGO_SETTINGS_MODULE }}'
    edx_django_service_repos: '{{ ECOMMERCE_REPOS }}'
    edx_django_service_environment_extra: '{{ ecommerce_environment }}'
    edx_django_service_gunicorn_extra: '{{ ECOMMERCE_GUNICORN_EXTRA }}'
    edx_django_service_gunicorn_port: '{{ ecommerce_gunicorn_port }}'
    edx_django_service_gunicorn_worker_class: "{{ ECOMMERCE_GUNICORN_WORKER_CLASS }}"
    edx_django_service_gunicorn_max_requests: "{{ ECOMMERCE_GUNICORN_MAX_REQUESTS }}"
    edx_django_service_gunicorn_workers: "{{ ECOMMERCE_GUNICORN_WORKERS }}"
    edx_django_service_nginx_port: '{{ ECOMMERCE_NGINX_PORT }}'
    edx_django_service_ssl_nginx_port: '{{ ECOMMERCE_SSL_NGINX_PORT }}'
    edx_django_service_use_python3: false
    edx_django_service_post_migrate_commands: '{{ ecommerce_post_migrate_commands }}'
    edx_django_service_basic_auth_exempted_paths_extra:
      - payment
      - \.well-known/apple-developer-merchantid-domain-association
    edx_django_service_automated_users: '{{ ECOMMERCE_AUTOMATED_USERS }}'
    edx_django_service_enable_newrelic_distributed_tracing: '{{ ECOMMERCE_ENABLE_NEWRELIC_DISTRIBUTED_TRACING }}'
    EDX_DJANGO_SERVICE_ENABLE_ADMIN_URLS_RESTRICTION: '{{ ECOMMERCE_ENABLE_ADMIN_URLS_RESTRICTION }}'
    EDX_DJANGO_SERVICE_ADMIN_URLS: '{{ ECOMMERCE_ADMIN_URLS }}'
  - role: antivirus
    ANTIVIRUS_SCAN_DIRECTORY: "{{ ECOMMERCE_ANTIVIRUS_SCAN_DIRECTORY }}"
    when: ECOMMERCE_ENABLE_ANTIVIRUS
