---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://openedx.atlassian.net/wiki/display/OpenOPS
# code style: https://openedx.atlassian.net/wiki/display/OpenOPS/Ansible+Code+Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
##
# Role includes for role ansible-role-django-ida

dependencies:
  - role: edx_django_service
    edx_django_service_version: '{{ DESIGNER_VERSION }}'
    edx_django_service_name: '{{ designer_service_name }}'
    edx_django_service_debian_pkgs_extra: '{{ designer_debian_pkgs }}'
    edx_django_service_gunicorn_port: '{{ designer_gunicorn_port }}'
    edx_django_service_repos: '{{ DESIGNER_REPOS }}'
    edx_django_service_django_settings_module: '{{ DESIGNER_DJANGO_SETTINGS_MODULE }}'
    edx_django_service_environment_extra: '{{ designer_environment }}'
    edx_django_service_gunicorn_extra: '{{ DESIGNER_GUNICORN_EXTRA }}'
    edx_django_service_nginx_port: '{{ DESIGNER_NGINX_PORT }}'
    edx_django_service_ssl_nginx_port: '{{ DESIGNER_SSL_NGINX_PORT }}'
    edx_django_service_memcache: '{{ DESIGNER_MEMCACHE }}'
    edx_django_service_automated_users: '{{ DESIGNER_AUTOMATED_USERS }}'
    edx_django_service_cors_whitelist: '{{ DESIGNER_CORS_ORIGIN_WHITELIST }}'
    edx_django_service_post_migrate_commands: '{{ designer_post_migrate_commands }}'
    edx_django_service_enable_newrelic_distributed_tracing: '{{ DESIGNER_ENABLE_NEWRELIC_DISTRIBUTED_TRACING }}'
